[package]
name = "certbot-wrapper"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"

[dependencies]
clap = "2.32"

[profile.release]
opt-level = "z"
lto = true
