[package]
name = "renew-letsencrypt-certs"
version = "0.1.0"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
edition = "2018"

[dependencies]
clap = "2.32"

[profile.release]
lto = true
